# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KoshQon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KoshQon
  pod 'SnapKit'
  pod 'PanModal'
  pod 'ProgressHUD'
  pod 'RSKImageCropper'
  pod 'KeychainSwift'
  pod 'ContextMenuSwift'
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'alamofire5'
  pod 'SVProgressHUD'
pod 'UIView-Shimmer'

end
